security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_requerant_provider:
      entity:
        class: MonIndemnisationJustice\Entity\Requerant
        property: email
    agent_provider:
      id: MonIndemnisationJustice\Security\Provider\AgentProvider
  role_hierarchy:
    ROLE_AGENT: [ ROLE_USER ]
    ROLE_AGENT_GESTION_PERSONNEL: [ ROLE_AGENT ]
    ROLE_AGENT_REDACTEUR: [ ROLE_AGENT ]
    ROLE_AGENT_VALIDATEUR: [ ROLE_REDACTEUR ]
    ROLE_REQUERANT: [ ROLE_USER ]
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    requerant:
      pattern: ^/(requerant|connexion-requerant)
      user_checker: MonIndemnisationJustice\Security\RequerantChecker
      lazy: true
      provider: app_requerant_provider
      form_login:
        login_path: app_login
        check_path: securite_connexion_requerant
        enable_csrf: true
        default_target_path: requerant_home_index
        form_only: true
      login_throttling:
        max_attempts: 5
        interval: '20 minutes'
        limiter: security.limitateur_connexion
      custom_authenticator: MonIndemnisationJustice\Security\Authenticator\FranceConnectAuthenticator
      entry_point: form_login
      logout:
        path: app_logout
        # where to redirect after logout
        target: app_login
    agent:
      pattern: ^/(api/agent|agent)
      lazy: true
      provider: agent_provider
      custom_authenticator: MonIndemnisationJustice\Security\Authenticator\ProConnectAuthenticator
      logout:
        path: agent_securite_deconnexion
        target: app_login
      switch_user: true


  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/requerant/, roles: ROLE_REQUERANT }
    #- { path: ^/agent/connexion, role: PUBLIC_ACCESS }
    - { path: ^/(agent|api/agent), roles: ROLE_AGENT }

when@test:
  security:
    password_hashers:
      # By default, password hashers are resource intensive and take time. This is
      # important to generate secure password hashes. In tests however, secure hashes
      # are not important, waste resources and increase test times. The following
      # reduces the work factor to the lowest possible values.
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
    firewalls:
      requerant:
        login_throttling: false
